# data encoding 

In [2]:
#data encoding >> converting categorical columns into numeric 

In [6]:
# 3 ways 
# nomila / one hot encoding 
#label and ordinal encoding 
# target guided ordinal encoding 

In [12]:
# NOMINAL / OHE >> BINARY VECTOR FOR EACH OF THE CATEGORIES 
# EXAMPLE SINGLE , MARID , SERORATED 
# [ 1,0,O] , [0,1,0] , [0,0,1]

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [24]:
df = pd.DataFrame({"status" : [ "single" , "married" , "serparated", "single" , "married" ]})

In [26]:
df

status
0      single
1     married
2  serparated
3      single
4     married

In [28]:
encoder = OneHotEncoder()

In [32]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [34]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [36]:
encoder.get_feature_names_out()

array(['status_married', 'status_serparated', 'status_single'],
      dtype=object)

In [42]:
encoded_df = pd.DataFrame(encoded , columns = encoder.get_feature_names_out())

In [44]:
encoded_df

status_married  status_serparated  status_single
0             0.0                0.0            1.0
1             1.0                0.0            0.0
2             0.0                1.0            0.0
3             0.0                0.0            1.0
4             1.0                0.0            0.0

In [48]:
encoder.transform([['single']]).toarray()

E:\anaconda hehehe\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [50]:
# pd.get_dummies() >> another way to do OHE

In [62]:
pd.get_dummies(df , dtype = int)

status_married  status_serparated  status_single
0               0                  0              1
1               1                  0              0
2               0                  1              0
3               0                  0              1
4               1                  0              0

In [54]:
df

status
0      single
1     married
2  serparated
3      single
4     married

In [56]:
df1 = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
                   'C': [1, 2, 3]})


In [58]:
df1

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [60]:
pd.get_dummies(df1)

C    A_a    A_b    B_a    B_b    B_c
0  1   True  False  False   True  False
1  2  False   True   True  False  False
2  3   True  False  False  False   True

In [68]:
pd.concat([df , encoded_df] , axis = 1)

status  status_married  status_serparated  status_single
0      single             0.0                0.0            1.0
1     married             1.0                0.0            0.0
2  serparated             0.0                1.0            0.0
3      single             0.0                0.0            1.0
4     married             1.0                0.0            0.0

In [72]:
import seaborn as sns 
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# LABEL ENcodING >> ASSINGN UNIQUE VAL/ LABEL RO CATEGORIES

In [77]:
# USING MAP FUNC OR LIB 

In [81]:
from sklearn.preprocessing import LabelEncoder

In [83]:
label_encoder = LabelEncoder()

In [87]:
label_encoder.fit_transform(df[['status']])

E:\anaconda hehehe\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [93]:
label_encoder.transform([['serparated' ]])

E:\anaconda hehehe\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [95]:
# ORDINAL ENCODING 

In [97]:
#high scl: 1
# garduation : 2
# postG : 3
# phd : 4

In [99]:
from sklearn.preprocessing import OrdinalEncoder

In [101]:
df = pd.DataFrame({"qualification": ["HS","GR", "PG", "PHD", "HS", "PHD"]})

In [103]:
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [109]:
# encoder = OrdinalEncoder()

In [115]:
encoder = OrdinalEncoder(categories =[[ "HS" , "GR" , "PG" , "PHD"]])

In [117]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [119]:
# new data 

In [121]:
encoder.transform([["PG"]])

E:\anaconda hehehe\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [125]:
# tARGET GUIDED ENCODING 

In [133]:
# relationship bw target varibale 
# used when lot of unique categorial 
# replace the category wwith  the mean and median of respactive grp"

In [135]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [137]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [145]:
mean_price= df.groupby('time')['total_bill'].mean().to_dict()

In [149]:
df['time_encoded'] = df['time'].map(mean_price)

In [151]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [154]:
# NOMINAL / OHE >> BINARY VECTOR FOR EACH OF THE CATEGORIES 

In [164]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [172]:
df = sns.load_dataset('iris')

In [174]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [176]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [178]:
df = sns.load_dataset('planets')

In [180]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [190]:
df.method.unique()

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

In [226]:
df.dropna(inplace = True)

In [194]:
# target guided endcoding 

In [196]:
from sklearn.preprocessing import TargetEncoder

In [218]:
target_enc = TargetEncoder()

In [228]:
df['method_encoded'] = target_enc.fit_transform(df[['method']], df[['orbital_period']])


E:\anaconda hehehe\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [230]:
df

method  number  orbital_period    mass  distance  year  \
0    Radial Velocity       1       269.30000   7.100     77.40  2006   
1    Radial Velocity       1       874.77400   2.210     56.95  2008   
2    Radial Velocity       1       763.00000   2.600     19.84  2011   
3    Radial Velocity       1       326.03000  19.400    110.62  2007   
4    Radial Velocity       1       516.22000  10.500    119.47  2009   
..               ...     ...             ...     ...       ...   ...   
640  Radial Velocity       1       111.70000   2.100     14.90  2009   
641  Radial Velocity       1         5.05050   1.068     44.46  2013   
642  Radial Velocity       1       311.28800   1.940     17.24  1999   
649          Transit       1         2.70339   1.470    178.00  2013   
784  Radial Velocity       3       580.00000   0.947    135.00  2012   

     method_encoded  
0        795.162413  
1        907.135154  
2        775.230989  
3        872.443542  
4        872.443542  
..              ...  
640      795.162413  
641      795.162413  
642      795.162413  
649      837.107427  
784      907.135154  

[498 rows x 7 columns]

In [232]:
# using by function 

In [234]:
mean_val= df.groupby('method')['orbital_period'].mean()

In [236]:
mean_val

method
Radial Velocity    837.454878
Transit              2.703390
Name: orbital_period, dtype: float64

In [240]:
df['new_mean_encoded'] = df['method'].map(mean_val)

In [242]:
df

method  number  orbital_period    mass  distance  year  \
0    Radial Velocity       1       269.30000   7.100     77.40  2006   
1    Radial Velocity       1       874.77400   2.210     56.95  2008   
2    Radial Velocity       1       763.00000   2.600     19.84  2011   
3    Radial Velocity       1       326.03000  19.400    110.62  2007   
4    Radial Velocity       1       516.22000  10.500    119.47  2009   
..               ...     ...             ...     ...       ...   ...   
640  Radial Velocity       1       111.70000   2.100     14.90  2009   
641  Radial Velocity       1         5.05050   1.068     44.46  2013   
642  Radial Velocity       1       311.28800   1.940     17.24  1999   
649          Transit       1         2.70339   1.470    178.00  2013   
784  Radial Velocity       3       580.00000   0.947    135.00  2012   

     method_encoded  new_mean_encoded  
0        795.162413        837.454878  
1        907.135154        837.454878  
2        775.230989        837.454878  
3        872.443542        837.454878  
4        872.443542        837.454878  
..              ...               ...  
640      795.162413        837.454878  
641      795.162413        837.454878  
642      795.162413        837.454878  
649      837.107427          2.703390  
784      907.135154        837.454878  

[498 rows x 8 columns]

In [246]:
df.method_encoded.unique()

array([795.16241261, 907.13515376, 775.23098943, 872.4435417 ,
       837.10742714, 837.10742714])

In [248]:
df.new_mean_encoded.unique()

array([837.45487848,   2.7033904 ])

In [326]:
df = sns.load_dataset('tips')

In [328]:
encoder = TargetEncoder()

In [330]:
 df['endoded'] = encoder.fit_transform(df[['time']] , df[['tip']])

In [332]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [334]:
df

total_bill   tip     sex smoker   day    time  size   endoded
0         16.99  1.01  Female     No   Sun  Dinner     2  3.122028
1         10.34  1.66    Male     No   Sun  Dinner     3  3.103412
2         21.01  3.50    Male     No   Sun  Dinner     3  3.103412
3         23.68  3.31    Male     No   Sun  Dinner     2  3.103412
4         24.59  3.61  Female     No   Sun  Dinner     4  3.013744
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  3.013744
240       27.18  2.00  Female    Yes   Sat  Dinner     2  3.122028
241       22.67  2.00    Male    Yes   Sat  Dinner     2  3.103412
242       17.82  1.75    Male     No   Sat  Dinner     2  3.174086
243       18.78  3.00  Female     No  Thur  Dinner     2  3.095026

[244 rows x 8 columns]

In [336]:
import warnings
warnings.filterwarnings('ignore')


In [338]:
# ordinal encdoing 

In [340]:
df.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [342]:
from sklearn.preprocessing import OrdinalEncoder

In [350]:
encode = OrdinalEncoder( categories= [['Sat', 'Sun', 'Thur', 'Fri']])

In [352]:
df['day_endcoded'] = encode.fit_transform(df[['day']])

In [354]:
df

total_bill   tip     sex smoker   day    time  size   endoded  \
0         16.99  1.01  Female     No   Sun  Dinner     2  3.122028   
1         10.34  1.66    Male     No   Sun  Dinner     3  3.103412   
2         21.01  3.50    Male     No   Sun  Dinner     3  3.103412   
3         23.68  3.31    Male     No   Sun  Dinner     2  3.103412   
4         24.59  3.61  Female     No   Sun  Dinner     4  3.013744   
..          ...   ...     ...    ...   ...     ...   ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3  3.013744   
240       27.18  2.00  Female    Yes   Sat  Dinner     2  3.122028   
241       22.67  2.00    Male    Yes   Sat  Dinner     2  3.103412   
242       17.82  1.75    Male     No   Sat  Dinner     2  3.174086   
243       18.78  3.00  Female     No  Thur  Dinner     2  3.095026   

     day_endcoded  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0  
..            ...  
239           0.0  
240           0.0  
241           0.0  
242           0.0  
243           2.0  

[244 rows x 9 columns]

In [302]:
df[['time', 'day_endcoded']]

time  day_endcoded
0    Dinner           2.0
1    Dinner           2.0
2    Dinner           2.0
3    Dinner           2.0
4    Dinner           2.0
..      ...           ...
239  Dinner           1.0
240  Dinner           1.0
241  Dinner           1.0
242  Dinner           1.0
243  Dinner           3.0

[244 rows x 2 columns]

In [308]:
df.groupby('day')['day_endcoded'].count()

day
Thur    62
Fri     19
Sat     87
Sun     76
Name: day_endcoded, dtype: int64

In [310]:
from sklearn.preprocessing import LabelEncoder

In [312]:
label = LabelEncoder()

In [314]:
df['label'] = label.fit_transform(df[['day']])

In [316]:
df

total_bill   tip     sex smoker   day    time  size   endoded  \
0         16.99  1.01  Female     No   Sun  Dinner     2  3.073654   
1         10.34  1.66    Male     No   Sun  Dinner     3  3.001617   
2         21.01  3.50    Male     No   Sun  Dinner     3  3.073654   
3         23.68  3.31    Male     No   Sun  Dinner     2  3.222988   
4         24.59  3.61  Female     No   Sun  Dinner     4  3.073654   
..          ...   ...     ...    ...   ...     ...   ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3  3.001617   
240       27.18  2.00  Female    Yes   Sat  Dinner     2  3.073654   
241       22.67  2.00    Male    Yes   Sat  Dinner     2  3.140215   
242       17.82  1.75    Male     No   Sat  Dinner     2  3.001617   
243       18.78  3.00  Female     No  Thur  Dinner     2  3.073654   

     day_endcoded  label  
0             2.0      2  
1             2.0      2  
2             2.0      2  
3             2.0      2  
4             2.0      2  
..            ...    ...  
239           1.0      1  
240           1.0      1  
241           1.0      1  
242           1.0      1  
243           3.0      3  

[244 rows x 10 columns]

In [318]:
df.label.unique()

array([2, 1, 3, 0])

In [356]:
# Label encoding and ordinal encoding are both techniques for converting categorical data into numerical format,
# but they differ in how they handle categorical variables with inherent order. 
# Label encoding assigns a unique integer to each category without considering any relationship between them,
# while ordinal encoding assigns integers based on the order or rank of categories

In [358]:
# label me direct kr dega int assign 

In [360]:
# but ordinal me categorical parameter ,me jo apn denge wahi krega 