In [117]:
import pandas as pd
import numpy as np
import seaborn as sns

In [118]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=2, random_state=1)

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3 , random_state=1)

In [121]:
X_train

array([[-1.49443258,  1.40169492,  2.29476412, ...,  1.93226104,
         3.49367948,  3.12132054],
       [ 0.41958848, -5.45711657,  1.44632656, ..., -5.61850444,
         1.20599872, -1.66919385],
       [ 0.97612811,  1.72644137,  0.76249546, ..., -0.22393567,
         1.40838494,  0.63388159],
       ...,
       [-2.35212068,  0.23908116,  2.89741304, ...,  1.74196068,
         2.31149047,  2.90591683],
       [ 4.68417171, -1.61566422, -0.84913094, ..., -5.6453817 ,
        -1.57766386, -3.51037444],
       [-0.30651465,  2.01618722,  0.61922592, ...,  0.98677735,
         2.83370907,  1.53009611]])

In [122]:
from sklearn.model_selection import  GridSearchCV

In [181]:
params = {"penalty": ("l1", "l2", "elasticnet"), 'C': [1, 2, 10, 20, 30, 40]}

In [124]:
from sklearn.linear_model import LogisticRegression

In [125]:
logstic = LogisticRegression()

In [126]:
logstic

LogisticRegression()

In [127]:
grid = GridSearchCV(logstic , param_grid= params , cv =5 , verbose = 2 )

In [128]:
grid

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=2)

In [129]:
grid.fit(X_train , y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ............................C=1, penalty=elasticnet; total time=   0.0s
[CV] END ............................C=1, penalt

E:\anaconda hehehe\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
60 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=2)

In [130]:
grid.best_estimator_

LogisticRegression(C=1)

In [131]:
grid.best_params_

{'C': 1, 'penalty': 'l2'}

In [132]:
grid.best_score_

0.8042857142857145

In [133]:
# two ways to pred  - 1st direclty use best_est or make custom model
y_pred = grid.best_estimator_.predict(X_test)

In [134]:
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [135]:
model= LogisticRegression(C=1 , penalty='l2')

In [136]:
model.fit(X_train , y_train)

LogisticRegression(C=1)

In [137]:
model.predict(X_test)

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [138]:
from sklearn. metrics import accuracy_score

In [139]:
accuracy_score(y_test , y_pred)

0.8433333333333334

# RANDOM SEARCH CV WITH LOGISTIC REG

In [165]:
from sklearn.model_selection import RandomizedSearchCV

In [193]:
random = RandomizedSearchCV(estimator=logstic , param_distributions=params , cv =5 , n_iter = 5 , scoring='accuracy' , verbose=2)

In [195]:
random

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=5,
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')},
                   scoring='accuracy', verbose=2)

In [197]:
random.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ...................................C=10, penalty=l2; total time=   0.0s
[CV] END ...................................C=10, penalty=l2; total time=   0.0s
[CV] END ...................................C=10, penalty=l2; total time=   0.0s
[CV] END ...................................C=10, penalty=l2; total time=   0.0s
[CV] END ...................................C=10, penalty=l2; total time=   0.0s
[CV] END ...................................C=40, penalty=l1; total time=   0.0s
[CV] END ...................................C=40, penalty=l1; total time=   0.0s
[CV] END ...................................C=40, penalty=l1; total time=   0.0s
[CV] END ...................................C=40, penalty=l1; total time=   0.0s
[CV] END ...................................C=40, penalty=l1; total time=   0.0s
[CV] END ...........................C=20, penalty=elasticnet; total time=   0.0s
[CV] END ...........................C=20, penalty

E:\anaconda hehehe\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
15 fits failed out of a total of 25.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda hehehe\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=5,
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')},
                   scoring='accuracy', verbose=2)

In [199]:
random.best_estimator_

LogisticRegression(C=10)

In [201]:
random.best_params_

{'penalty': 'l2', 'C': 10}

In [203]:
y_pred = random.best_estimator_.predict(X_test)

In [205]:
acc_ran = accuracy_score(y_test , y_pred)

In [207]:
acc_ran

0.8433333333333334

In [213]:
random.predict_proba(X_test)

array([[0.01879749, 0.98120251],
       [0.83898036, 0.16101964],
       [0.7108899 , 0.2891101 ],
       [0.86747153, 0.13252847],
       [0.44957131, 0.55042869],
       [0.90848146, 0.09151854],
       [0.03713293, 0.96286707],
       [0.6996359 , 0.3003641 ],
       [0.87856452, 0.12143548],
       [0.04226844, 0.95773156],
       [0.91430292, 0.08569708],
       [0.57980799, 0.42019201],
       [0.27538389, 0.72461611],
       [0.76873495, 0.23126505],
       [0.41773584, 0.58226416],
       [0.32975909, 0.67024091],
       [0.05024098, 0.94975902],
       [0.13944626, 0.86055374],
       [0.02893281, 0.97106719],
       [0.92867937, 0.07132063],
       [0.55035685, 0.44964315],
       [0.0426032 , 0.9573968 ],
       [0.18883848, 0.81116152],
       [0.90146352, 0.09853648],
       [0.0899755 , 0.9100245 ],
       [0.44390846, 0.55609154],
       [0.86017942, 0.13982058],
       [0.54146069, 0.45853931],
       [0.49065506, 0.50934494],
       [0.82646531, 0.17353469],
       [0.