In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

In [12]:
df = sns.load_dataset('tips')

In [13]:
# predict what is the time ? if any person is visiting ? lunch or dinner , ? timw is target

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [15]:
df.duplicated().sum()

1

In [16]:
df = df.drop_duplicates()

In [17]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [18]:
# since time is nomnial  varibale , then we will use label encoding 

In [19]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [20]:
# since the time col is categoircal data , we will encode them 

In [21]:
#time is nomial varibale >> then wil use label encoder

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['time'] = encoder.fit_transform(df['time'])

In [23]:
df.time.unique()

array([0, 1])

In [24]:
X = df.drop('time' , axis  = 1)
y = df['time']

In [25]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state=1)

In [26]:
# handlding mssing vale  , encoding , feature scaling 

# FOR MISSING VALUE TREATMENT OF MISSING VALUE TREATMENT 

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [30]:
# now pipline and column transformer 

In [31]:
# Pipeline
# Pipeline is a way to chain multiple steps (preprocessing + model) into one object so your whole ML flow becomes a single unit.

# Example flow:

# Scaling → Encoding → Model training


# All run together with:

# fit() → transform() → predict()


# Why it’s useful:

# No data leakage

# Clean, organized code

# Works perfectly with GridSearchCV

# Reproducible workflow

In [32]:
# ColumnTransformer
# ColumnTransformer is used when different columns need different preprocessing.

# Real data has:

# Numerical columns → scaling

# Categorical columns → encoding

# ColumnTransformer handles this in one place.

In [33]:
from sklearn.pipeline import Pipeline # seqnece of data transformer


In [34]:
from sklearn.compose import ColumnTransformer # groups all the piplines steps for each of the columns

In [35]:
cat_cols = ["sex" ,"smoker" , "day"]
num_cols = [ 'tip' , 'size']

In [36]:
cat_cols

['sex', 'smoker', 'day']

In [37]:
num_cols

['tip', 'size']

In [38]:
# feATURE ENGG AUTOMATION USING PIPLINE AND COL TRANSFORMER 

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

numerical_pipeline = Pipeline(steps=[
    ("imputation", SimpleImputer(strategy="median")),
    ("scaling", StandardScaler())
])

categorical_pipeline = Pipeline(steps=[
    ("imputation", SimpleImputer(strategy="most_frequent")),
    ("encoding", OneHotEncoder(handle_unknown="ignore"))
])


In [40]:
preprocessor = ColumnTransformer(transformers=[
    ("numerical_pipeline", numerical_pipeline, num_cols),
    ("categorical_columns", categorical_pipeline, cat_cols)
])

In [41]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [42]:
X_train

array([[-1.43331971, -0.57582667,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.70999378,  1.51221771,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02063848, -0.57582667,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.38595461, -0.57582667,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [-1.44062603, -0.57582667,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.07178274,  0.46819552,  1.        , ...,  1.        ,
         0.        ,  0.        ]])

In [43]:
X_test

array([[-1.44062603, -1.61984886,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.02063848, -0.57582667,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.3201977 ,  0.46819552,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [-0.34467765, -0.57582667,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.02063848, -0.57582667,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [-1.11914784, -0.57582667,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [-0.88534552, -0.57582667,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        

In [44]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [45]:
models = {"support vector classifier": SVC(), 
         "DT Classifier": DecisionTreeClassifier(),
         "Log reg": LogisticRegression()}
models

{'support vector classifier': SVC(),
 'DT Classifier': DecisionTreeClassifier(),
 'Log reg': LogisticRegression()}

In [46]:
for i in range(len(models)):
    print(list(models.values())[i]) # values bcz it is value 

SVC()
DecisionTreeClassifier()
LogisticRegression()


In [47]:
from sklearn.metrics import accuracy_score

In [95]:
def model_train_eval(X_train , X_test , y_train , y_test , models):
    evaluation = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(X_train , y_train)
        y_pred = model.predict(X_test)
        model_score = accuracy_score(y_test , y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation

In [97]:
model_train_eval(X_train , X_test , y_train ,y_test,models)

{'support vector classifier': 0.9387755102040817,
 'DT Classifier': 0.9591836734693877,
 'Log reg': 0.9387755102040817}

In [101]:
models = {
    "Logistic Regression": LogisticRegression(),
}

results = model_train_eval(X_train, X_test, y_train, y_test, models)
print(results)


{'Logistic Regression': 0.9387755102040817}
